import pytest
from backend.budget import session as sess

SECRET = "0" * 64  # 32-byte hex


def test_sign_then_verify_roundtrip():
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    assert sess.verify(SECRET, "cookie:abc", "2026-05-17", token) is True


def test_verify_fails_on_tampered_token():
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    tampered = token[:-1] + ("A" if token[-1] != "A" else "B")
    assert sess.verify(SECRET, "cookie:abc", "2026-05-17", tampered) is False


def test_verify_fails_on_wrong_cookie():
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    assert sess.verify(SECRET, "cookie:xyz", "2026-05-17", token) is False


def test_verify_fails_on_wrong_date():
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    assert sess.verify(SECRET, "cookie:abc", "2026-05-18", token) is False


def test_verify_fails_on_wrong_secret():
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    other = "1" * 64
    assert sess.verify(other, "cookie:abc", "2026-05-17", token) is False


def test_token_is_url_safe_base64():
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    import string
    allowed = string.ascii_letters + string.digits + "-_="
    assert all(ch in allowed for ch in token)


def test_token_has_no_base64_padding():
    # Cross-language symmetry: Node base64url strips =, Python must too.
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    assert "=" not in token


def test_token_length_is_43_chars():
    # HMAC-SHA256 → 32 bytes → 43 chars urlsafe_b64encode without padding.
    token = sess.sign(SECRET, "cookie:abc", "2026-05-17")
    assert len(token) == 43


def test_verify_returns_false_on_none_token():
    assert sess.verify(SECRET, "cookie:abc", "2026-05-17", None) is False  # type: ignore[arg-type]


def test_verify_returns_false_on_empty_token():
    assert sess.verify(SECRET, "cookie:abc", "2026-05-17", "") is False


def test_verify_returns_false_on_non_string_token():
    assert sess.verify(SECRET, "cookie:abc", "2026-05-17", 12345) is False  # type: ignore[arg-type]


def test_known_node_compatible_vector():
    # Frozen cross-language vector. The expected token below was generated by Node:
    #   node -e "console.log(require('crypto').createHmac('sha256','test-secret').update('cookie:abc:2026-05-17').digest('base64url'))"
    # If this assertion ever fails the Python↔Node base64url contract has drifted
    # (likely a regression in the .rstrip(b'=') of session.sign).
    EXPECTED = "J_u5epCQdh50mMvug4hyVYgWeOieBFxeulnVMmlJcRc"
    token = sess.sign("test-secret", "cookie:abc", "2026-05-17")
    assert token == EXPECTED
    assert sess.verify("test-secret", "cookie:abc", "2026-05-17", token) is True
